### ISSUE TITLE
跑example中的csv_agent.py，出现问题

### ISSUE THREAD

**Issue by cheng18175030250** [dyfsquall/tongyi_qwen_langchain#2]
我跑了csv_agent.py，出现如下问题，请问是怎么回事

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[22], line 2
      1 from langchain.agents import load_tools, AgentType, initialize_agent
----> 2 from langchain_qianwen import Qwen_v1
      4 if __name__ == "__main__":
      5     llm = Qwen_v1(
      6         # model_name="qwen-plus",
      7         model_name="qwen-turbo",
      8         # temperature=0.1,
      9     )

File /Users/CX/PyProject/venv/lib/python3.9/site-packages/langchain_qianwen/__init__.py:1
----> 1 from .qwen_llm import Qwen_v1, BaseDashScope
      2 from .qwen_chat_model import ChatQwen_v1
      4 __all__ = [
      5     "Qwen_v1",
      6     "ChatQwen_v1",
      7     "BaseDashScope",
      8 ]

File /Users/CX/PyProject/venv/lib/python3.9/site-packages/langchain_qianwen/qwen_llm.py:13
     10 from langchain.schema.output import GenerationChunk
     11 from langchain.callbacks.manager import (CallbackManagerForLLMRun, AsyncCallbackManagerForLLMRun)
---> 13 from .commons import completion_with_retry, acompletion_with_retry, response_text_format, response_handler
     14 from http import HTTPStatus
     16 logger = logging.getLogger(__name__)

File /Users/CX/PyProject/venv/lib/python3.9/site-packages/langchain_qianwen/commons.py:16
     10 from typing import Optional, Union, Callable, Any, AsyncGenerator
     12 logger = logging.getLogger(__name__)
     15 def completion_with_retry(
---> 16     llm_model: BaseLLM | BaseChatModel,
     17     run_manager: Optional[CallbackManagerForLLMRun] = None,
     18     **kwargs: Any
     19 ) -> Any:
     20     """Use tenacity to retry the completion call."""
     21     retry_decorator = _create_retry_decorator(llm_model, run_manager=run_manager)

TypeError: unsupported operand type(s) for |: 'ModelMetaclass' and 'ModelMetaclass'

**Comment by devinyf** [comment]
是 langchain 最近几次的更新有比较大的改变...

csv 检索的最新使用方法请查看 langchain 的官方文档:
https://python.langchain.com/docs/integrations/toolkits/csv

example code:
```python
from langchain.agents.agent_types import AgentType
from langchain_experimental.agents.agent_toolkits import create_csv_agent
from langchain_openai import ChatOpenAI, OpenAI
```

注意 create_csv_agent 被迁移到了 langchain_experimental 独立的库中，可能需要单独安装

同时 langchain 本身已经合并的通义千问的功能, 应该已经迭代比较成熟了，建议优先使用以下方式调用:
```python
from langchain_community.llms.tongyi import Tongyi
```

这个仓库后续应该会被标记为 Archive 停止更新

谢谢

**Comment by devinyf** [comment]
我自己试了一下, 这个案例目前使用 `Tongyi` 还是会报错, 本仓库的 `Qwen_v1` 是没问题的

**Comment by cheng18175030250** [comment]
您好，create_csv_agent，AgentType这些更新我都考虑进去了，可以把你的本仓库的 Qwen_v1测试代码发一下么，我测试了好多次都有问题，万分感谢

**Comment by cheng18175030250** [comment]
> 我自己试了一下, 这个案例目前使用 `Tongyi` 还是会报错, 本仓库的 `Qwen_v1` 是没问题的

您好，create_csv_agent，AgentType这些更新我都考虑进去了，可以把你的本仓库的 Qwen_v1测试代码发一下么，我测试了好多次都有问题，万分感谢

**Comment by devinyf** [comment]
首先对齐一下库版本:
```
▶ pip list | grep langchain
langchain               0.1.7
langchain-community     0.0.20
langchain-core          0.1.23
langchain-experimental  0.0.51
langchain-qianwen       0.1.13
```

```python
from langchain.agents import AgentType
from langchain_experimental.agents.agent_toolkits import create_csv_agent

from langchain_qianwen import Qwen_v1
# from langchain_community.llms.tongyi import Tongyi

if __name__ == "__main__":
    llm = Qwen_v1(
        model_name="qwen-turbo",
    )

    csv_agent_executer = create_csv_agent(
        llm=llm,
        path="./assets/episode_info.csv",
        agent_type=AgentType.ZERO_SHOT_REACT_DESCRIPTION,
        verbose=True,
    )

    csv_agent_executer.run(
        """print seasons ascending order of the number of episodes in each season"""
    )
```
输出:
```
The dataframe has been grouped by season, counted the number of episodes for each season, sorted them in ascending order of episode count, and then reset the index. Now, I can provide the final answer.

Final Answer: The seasons, ordered by the number of episodes in ascending order, are as follows:

- Season 1: 5 episodes
- Season 2: 12 episodes
- Season 5: 21 episodes
- Season 9: 21 episodes
- Season 6: 22 episodes
- Season 8: 22 episodes
- Season 3: 23 episodes
- Season 4: 24 episodes
- Season 7: 24 episodes
```

**Comment by cheng18175030250** [comment]
> 首先对齐一下库版本:
> 
> ```
> ▶ pip list | grep langchain
> langchain               0.1.7
> langchain-community     0.0.20
> langchain-core          0.1.23
> langchain-experimental  0.0.51
> langchain-qianwen       0.1.13
> ```
> 
>  ```python
> from langchain.agents import AgentType
> from langchain_experimental.agents.agent_toolkits import create_csv_agent
> 
> from langchain_qianwen import Qwen_v1
> # from langchain_community.llms.tongyi import Tongyi
> 
> if __name__ == "__main__":
>     llm = Qwen_v1(
>         model_name="qwen-turbo",
>     )
> 
>     csv_agent_executer = create_csv_agent(
>         llm=llm,
>         path="./assets/episode_info.csv",
>         agent_type=AgentType.ZERO_SHOT_REACT_DESCRIPTION,
>         verbose=True,
>     )
> 
>     csv_agent_executer.run(
>         """print seasons ascending order of the number of episodes in each season"""
>     )
> ```
> 
> 输出:
> 
> ```
> The dataframe has been grouped by season, counted the number of episodes for each season, sorted them in ascending order of episode count, and then reset the index. Now, I can provide the final answer.
> 
> Final Answer: The seasons, ordered by the number of episodes in ascending order, are as follows:
> 
> - Season 1: 5 episodes
> - Season 2: 12 episodes
> - Season 5: 21 episodes
> - Season 9: 21 episodes
> - Season 6: 22 episodes
> - Season 8: 22 episodes
> - Season 3: 23 episodes
> - Season 4: 24 episodes
> - Season 7: 24 episodes
> ```

库版本和你的一致，copy上述代码后还是出现同样的问题，有可能是python版本的问题么，如果有的话，请问你的python是什么版本？

**Comment by devinyf** [comment]
▶ python -V
Python 3.10.13

**Comment by cheng18175030250** [comment]
> ▶ python -V
> Python 3.10.13

问题已解决，最后还有一个问题请教一下，比如我想利用qwen对"titanic.csv"文件进行探索，为什么总会出现“############################################################
kwargs:  {'prompt': '\nYou are working with a pandas dataframe in Python.”等等重复的语句（下图中非绿色的字体所示），之前测试gpt3.5就不会出现这种情况？
![1708478029676](https://github.com/devinyf/langchain_qianwen/assets/53423620/293415e3-7c0a-4112-8d62-390ea3f1ec49)

**Comment by devinyf** [comment]
应该是我上次修bug时 有调试信息没清理干净,
更新一下版本,  刚刚上传
```
langchain-qianwen       0.1.15
```
这个 github 仓库也同步更新了

**Comment by cheng18175030250** [comment]
> 应该是我上次修bug时 有调试信息没清理干净, 更新一下版本, 刚刚上传
> 
> ```
> langchain-qianwen       0.1.15
> ```
> 
> 这个 github 仓库也同步更新了

ok, 感谢
