### ISSUE TITLE
我在用langchain中的create_sql_agent时，使用qwen模型，总是没法可视化，但是我改成openai就可以绘制图像可视化，请问你知道怎么回事么？

### ISSUE THREAD

**Issue by cheng18175030250** [dyfsquall/tongyi_qwen_langchain#3]

**Comment by cheng18175030250** [comment]
感觉langchain中的很多agent还是不支持国内的大模型

**Comment by devinyf** [comment]
可视化  是指使用 python 代码解释器的功能画图么？？

**Comment by cheng18175030250** [comment]
> 可视化 是指使用 python 代码解释器的功能画图么？？

是的，create_csv_agent是可以plot的，但是create_sql_agent不行
<img width="959" alt="image" src="https://github.com/devinyf/langchain_qianwen/assets/53423620/31b0acc2-4406-49a7-be9d-2c19191106f8">

**Comment by devinyf** [comment]
是希望可以直接返回图片的 url 是吗？？
方便提供一下完整的测试代码吗？

**Comment by cheng18175030250** [comment]
> 是希望可以直接返回图片的 url 是吗？？
> 方便提供一下完整的测试代码吗？

https://github.com/hodgesmr/LangChain-Data-Demo/blob/main/LangChain%20Data%20Demo.ipynb
我把代码里的openai换成了本仓库的qwen_v1大模型，就无法绘图了

**Comment by devinyf** [comment]
> https://github.com/hodgesmr/LangChain-Data-Demo/blob/main/LangChain%20Data%20Demo.ipynb 我把代码里的openai换成了本仓库的qwen_v1大模型，就无法绘图了

可以尝试使用通义千问自带的插件:
 
我更新了代码解释器插件调用功能

使用方法参考: [code_interpreter_plugin example](https://github.com/devinyf/langchain_qianwen/blob/main/examples/code_interpreter_plugin_tools.py)

ps. 需要去开通灵积平台插件的插件权限: https://dashscope.console.aliyun.com/plugin

返回 markdown 格式的图片链接
<img width="814" alt="image" src="https://github.com/devinyf/langchain_qianwen/assets/31347811/6533cb80-12cf-4bfd-8ad0-faa99f8a70c1">

希望能解决你遇到的问题

**Comment by cheng18175030250** [comment]
感谢

**Comment by cheng18175030250** [comment]
请问这个生成的图像只能生成到阿里云上么，不能不传到云上，只在本地保存么？

**Comment by devinyf** [comment]
> 请问这个生成的图像只能生成到阿里云上么，不能不传到云上，只在本地保存么？

图像是在云端生成的, 所以仅返回了url路径。 可以自己写个函数 将url下载到本地使用

**Comment by cheng18175030250** [comment]
> > 请问这个生成的图像只能生成到阿里云上么，不能不传到云上，只在本地保存么？
> 
> 图像是在云端生成的, 所以仅返回了url路径。 可以自己写个函数 将url下载到本地使用

所以没法让图像在本地生成是不是，我看qwen好像把code interpreter这个插件封装了，也没找到源码

**Comment by cheng18175030250** [comment]
官方回答了，只能在云端生成。
请问咱们仓库这个模型可以使用qwen-agent的code interpreter的插件么？https://github.com/QwenLM/Qwen-Agent/tree/main/qwen_agent/tools

**Comment by devinyf** [comment]
qwen-agent 和 langchain 是不同的 agent 实现, 不能混用的
我上面回复你的例子 其实就是 将 `code interpreter 插件` 封装成了 langchain-tools 来使用的。

**Comment by cheng18175030250** [comment]
ok 了解了 感谢
